-- use this file to map the AP item ids to your items
-- first value is the code of the target item and the second is the item type override. The third value is an optional increment multiplier for consumables. (feel free to expand the table with any other values you might need (i.e. special initial values, etc.)!)
-- here are the SM items as an example: https://github.com/Cyb3RGER/sm_ap_tracker/blob/main/scripts/autotracking/item_mapping.lua
BASE_ITEM_ID = 0
ITEM_MAPPING = {
	
	-- ANIMATRONICS
	[BASE_ITEM_ID + 1] = {{"golden_freddy_key", "toggle"}, {"salv1numb0", "progressive"}},
	[BASE_ITEM_ID + 2] = {{"endo_key", "toggle"}, {"salv1numb0", "progressive"}},
	[BASE_ITEM_ID + 3] = {{"toy_freddy_key", "toggle"}, {"salv2numb0", "progressive"}},
	[BASE_ITEM_ID + 4] = {{"toy_bonnie_key", "toggle"}, {"salv2numb0", "progressive"}},
	[BASE_ITEM_ID + 5] = {{"toy_chica_key", "toggle"}, {"salv2numb0", "progressive"}},
	[BASE_ITEM_ID + 6] = {{"mangle_key", "toggle"}, {"salv2numb0", "progressive"}},
	[BASE_ITEM_ID + 7] = {{"withered_freddy_key", "toggle"}, {"salv1numb0", "progressive"}},
	[BASE_ITEM_ID + 8] = {{"withered_bonnie_key", "toggle"}, {"salv1numb0", "progressive"}},
	[BASE_ITEM_ID + 9] = {{"withered_chica_key", "toggle"}, {"salv1numb0", "progressive"}},
	[BASE_ITEM_ID + 10] = {{"withered_foxy_key", "toggle"}, {"salv1numb0", "progressive"}},
	[BASE_ITEM_ID + 11] = {{"bb_key", "toggle"}},
	[BASE_ITEM_ID + 12] = {{"jj_key", "toggle"}, {"salv2numb0", "progressive"}},
	[BASE_ITEM_ID + 13] = {{"shadow_freddy_key", "toggle"}, {"salv3numb0", "progressive"}},
	[BASE_ITEM_ID + 14] = {{"rwqfsfasxc_key", "toggle"}, {"salv2numb0", "progressive"}},
	[BASE_ITEM_ID + 15] = {{"phantoms_key", "toggle"}, {"salv3numb0", "progressive"}},
	[BASE_ITEM_ID + 16] = {{"springtrap_key", "toggle"}},
	[BASE_ITEM_ID + 17] = {{"plushtrap_key", "toggle"}, {"salv4numb0", "progressive"}},
	[BASE_ITEM_ID + 18] = {{"nmfredbear_key", "toggle"}, {"salv4numb0", "progressive"}},
	[BASE_ITEM_ID + 19] = {{"nmbb_key", "toggle"}, {"salv4numb0", "progressive"}},
	[BASE_ITEM_ID + 20] = {{"nightmarionne_key", "toggle"}, {"salv4numb0", "progressive"}},
	[BASE_ITEM_ID + 21] = {{"lolbit_key", "toggle"}, {"salv5numb0", "progressive"}},
	[BASE_ITEM_ID + 22] = {{"circus_baby_key", "toggle"}, {"salv5numb0", "progressive"}},
	[BASE_ITEM_ID + 23] = {{"funtime_freddy_key", "toggle"}, {"salv5numb0", "progressive"}},
	[BASE_ITEM_ID + 24] = {{"funtime_foxy_key", "toggle"}, {"salv5numb0", "progressive"}},
	[BASE_ITEM_ID + 25] = {{"ballora_key", "toggle"}, {"salv5numb0", "progressive"}},
	[BASE_ITEM_ID + 26] = {{"helpy_key", "toggle"}, {"salv3numb0", "progressive"}},
	[BASE_ITEM_ID + 27] = {{"music_man_key", "toggle"}, {"salv3numb0", "progressive"}},
	[BASE_ITEM_ID + 28] = {{"hippo_key", "toggle"}, {"salv3numb0", "progressive"}},
	[BASE_ITEM_ID + 29] = {{"lefty_key", "toggle"}},
	[BASE_ITEM_ID + 30] = {{"molten_freddy_key", "toggle"}},
	[BASE_ITEM_ID + 31] = {{"scrap_baby_key", "toggle"}},
	[BASE_ITEM_ID + 32] = {{"twistedwolf_key", "toggle"}, {"salv4numb0", "progressive"}},
	[BASE_ITEM_ID + 33] = {{"malhare_key", "toggle"}, {"salv3numb0", "progressive"}},
	[BASE_ITEM_ID + 34] = {{"dreadbear_key", "toggle"}, {"salv4numb0", "progressive"}},
	[BASE_ITEM_ID + 35] = {{"lolzhax_key", "toggle"}, {"salv5numb0", "progressive"}},
	[BASE_ITEM_ID + 36] = {{"coffee_key", "toggle"}},
	[BASE_ITEM_ID + 37] = {{"anim_key", "toggle"}},
	[BASE_ITEM_ID + 38] = {{"chipper_key", "toggle"}},
	[BASE_ITEM_ID + 39] = {{"sparky_key", "toggle"}},
	[BASE_ITEM_ID + 40] = {{"candy_key", "toggle"}},
	[BASE_ITEM_ID + 41] = {{"popgoes_key", "toggle"}},
	[BASE_ITEM_ID + 42] = {{"rodney_key", "toggle"}},

    -- KEY ITEMS	
	[BASE_ITEM_ID + 43] = {{"progressive_present", "progressive"}},
	[BASE_ITEM_ID + 44] = {{"freddy_mask_key", "toggle"}},
	[BASE_ITEM_ID + 45] = {{"bonnie_mask_key", "toggle"}},
	[BASE_ITEM_ID + 46] = {{"chica_mask_key", "toggle"}},
	[BASE_ITEM_ID + 47] = {{"foxy_mask_key", "toggle"}},
	[BASE_ITEM_ID + 48] = {{"hachet_key", "toggle"}},
	[BASE_ITEM_ID + 49] = {{"parts_and_services_key", "toggle"}},
	[BASE_ITEM_ID + 50] = {{"keypad_code", "toggle"}},
	[BASE_ITEM_ID + 51] = {{"box_code", "progressive"}},

	-- UPGRADES
	[BASE_ITEM_ID + 52] = {{"backdoor_trading_upgrade", "progressive"}},
	[BASE_ITEM_ID + 53] = {{"progressive_mini_multiplier_upgrade", "progressive"}},
	[BASE_ITEM_ID + 54] = {{"cam_radar_upgrade", "progressive"}},
	[BASE_ITEM_ID + 55] = {{"felixs_loan_upgrade", "progressive"}},
	[BASE_ITEM_ID + 56] = {{"superfan_upgrade", "progressive"}},
	[BASE_ITEM_ID + 57] = {{"early_investment_upgrade", "progressive"}},
	[BASE_ITEM_ID + 58] = {{"power_ac_upgrade", "progressive"}},
	[BASE_ITEM_ID + 59] = {{"all_ears_upgrade", "progressive"}},
	[BASE_ITEM_ID + 60] = {{"head_start_upgrade", "progressive"}},
	[BASE_ITEM_ID + 61] = {{"employee_discount_upgrade", "progressive"}},
	[BASE_ITEM_ID + 62] = {{"bear_change_upgrade", "progressive"}},
	[BASE_ITEM_ID + 63] = {{"overcharge_upgrade", "progressive"}},
	[BASE_ITEM_ID + 64] = {{"power_hour_upgrade", "toggle"}},
	[BASE_ITEM_ID + 65] = {{"fuzzy_dice_upgrade", "toggle"}},
	[BASE_ITEM_ID + 66] = {{"upgrade_commander_upgrade", "toggle"}},
	[BASE_ITEM_ID + 67] = {{"overstock_upgrade", "progressive"}},
	[BASE_ITEM_ID + 68] = {{"retina_burner_upgrade", "progressive"}},
	[BASE_ITEM_ID + 69] = {{"spawnkiller_upgrade", "toggle"}},
	[BASE_ITEM_ID + 70] = {{"talbert_files", "toggle"}},
	[BASE_ITEM_ID + 71] = {{"cupcake_cart", "toggle"}},
	[BASE_ITEM_ID + 72] = {{"anim_cart", "toggle"}},
	[BASE_ITEM_ID + 73] = {{"mangle_cart", "toggle"}},

	-- MENDO SHOP ITEMS
	[BASE_ITEM_ID + 74] = {{"mimic_ball_shop", "toggle"}},
	[BASE_ITEM_ID + 75] = {{"kings_prize_shop_1", "progressive"}},
	[BASE_ITEM_ID + 76] = {{"rewind_clock_shop_1", "progressive"}},
	[BASE_ITEM_ID + 77] = {{"battery_pack_shop_1", "progressive"}},
	[BASE_ITEM_ID + 78] = {{"snowcone_shop_1", "progressive"}},
	[BASE_ITEM_ID + 79] = {{"golden_cupcake_shop_1", "progressive"}},
	[BASE_ITEM_ID + 80] = {{"ar_mask_shop_1", "progressive"}},
	[BASE_ITEM_ID + 81] = {{"laser_doors_shop_1", "progressive"}},
	[BASE_ITEM_ID + 82] = {{"bear_trap_shop", "toggle"}},
	[BASE_ITEM_ID + 83] = {{"death_coin_shop", "toggle"}},
	[BASE_ITEM_ID + 84] = {{"distortion_clock_shop_1", "progressive"}},
	[BASE_ITEM_ID + 85] = {{"pickles_shop", "toggle"}},
	[BASE_ITEM_ID + 86] = {{"chipper_lumber_shop", "toggle"}},
	[BASE_ITEM_ID + 87] = {{"token", "consumable", 1}}

}

